version: "3.9"

services:
  app:
    build: .
    container_name: telegram_pipeline_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # FastAPI
      - "3000:3000"  # Dagster if used
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: telegram_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: telegram_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
